### ISSUE TITLE
different estimation method？

### ISSUE THREAD

**Issue by zdj97** [cantabile-kwok/VoiceFlow-TTS#14]
Hi, what is the effect of different estimation method? And I met several problems when i changed different estimation method or change OT method.

**Comment by cantabile-kwok** [comment]
Hi, are you referring to the different model architectures for the vector field estimator? This repo only supports the 2D Unet proposed in GradTTS and 1D CNN in DiffSinger. I did not perform many experiments with DiffSinger, thus I do not have conclusions about the performance differences made by different estimator structures. Since the VoiceFlow paper focuses majorly on rectified flow, exploring the best model architecture is out of its scope. 

I think the OT sampling method is not correctly implemented at the time of the paper publication, and I did not re-investigate on this later. So the OT method is not directly usable here.

**Comment by zdj97** [comment]
Thanks, and i will explore other methods.
