### ISSUE TITLE
does the `cond` need to be projected to same channels in DiffSingerNet?

### ISSUE THREAD

**Issue by p0p4k** [cantabile-kwok/VoiceFlow-TTS#6]
This code does not work.
```
diffnet = DiffSingerNet()

x = torch.randn(2, 80, 10)
x_mask = torch.ones(2, 1, 10)
t = torch.tensor([1])
mu = torch.randn(2, 80, 10)

diffnet(x, x_mask, mu, t)
```
The following code works.
```
diffnet = DiffSingerNet()

x = torch.randn(2, 80, 10)
x_mask = torch.ones(2, 1, 10)
t = torch.tensor([1])
mu = torch.randn(2, 128, 10)

diffnet(x, x_mask, mu, t)
```

**Comment by p0p4k** [comment]
also, `cond = s + mu` means `mu` and `s` have to be in same dimensions and, `s` is output of a `mlp` with `encoder_hidden` out dimensions; but input `mu` and `x` are of `spec_dim` channels?

**Comment by p0p4k** [comment]
Ah, now i see the encoder_hidden and n_feats are 80 dims in the main tts model.

**Comment by cantabile-kwok** [comment]
Oh yes, sorry for any confusion! There might be some implicit requirements for the tensor dimensions. I will take a careful look later.

**Comment by p0p4k** [comment]
Your repo helped me implement pflow tts. So thanks for that. Am I correct that diffsinger is a modified wavenet decoder?

**Comment by cantabile-kwok** [comment]
In the diffsinger paper, they say "We adopt a non-causal WaveNet (Oord et al. 2016) architecture proposed by (Rethage, Pons, and Serra 2018; Kong et al. 2021) as our denoiser." So it is a non-causal version of WaveNet instead of the original WaveNet. The reference here is "Rethage, D.; Pons, J.; and Serra, X. 2018. A wavenet for speech denoising. In 2018 IEEE International Confer- ence on Acoustics, Speech and Signal Processing (ICASSP), 5069–5073. IEEE."
